services:
  mysql:
    image: mysql:8.0
    container_name: justaclick-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: justaclick
    ports:
      - "3306:3306"
    volumes:
      - justaclick_mysql:/var/lib/mysql

volumes:
  justaclick_mysql:
